/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.lab;

import java.io.IOException;
import javax.swing.JEditorPane;
import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.awt.ActionID;
import org.openide.awt.ActionReference;
import org.openide.util.Exceptions;
import org.openide.windows.TopComponent;
import org.openide.util.NbBundle.Messages;

/**
 * Top component which displays something.
 */
@ConvertAsProperties(
        dtd = "-//org.lab//sample//EN",
        autostore = false
)
@TopComponent.Description(
        preferredID = "sampleTopComponent",
        iconBase = "org/lab/myicon2.png",
        persistenceType = TopComponent.PERSISTENCE_ALWAYS
)
@TopComponent.Registration(mode = "webpreview", openAtStartup = true)
@ActionID(category = "Window", id = "org.lab.sampleTopComponent")
@ActionReference(path = "Menu/Window" /*, position = 333 */)
@TopComponent.OpenActionRegistration(
        displayName = "#CTL_sampleAction",
        preferredID = "sampleTopComponent"
)
@Messages({
    "CTL_sampleAction=sample",
    "CTL_sampleTopComponent=sample Window",
    "HINT_sampleTopComponent=This is a sample window"
})
public final class sampleTopComponent extends TopComponent {

    public sampleTopComponent() {
        initComponents();
        setName(Bundle.CTL_sampleTopComponent());
        setToolTipText(Bundle.HINT_sampleTopComponent());
        putClientProperty(TopComponent.PROP_CLOSING_DISABLED, Boolean.TRUE);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        webpage = new javax.swing.JEditorPane();

        setLayout(new java.awt.BorderLayout());

        webpage.setBorder(null);
        jScrollPane1.setViewportView(webpage);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JEditorPane webpage;
    // End of variables declaration//GEN-END:variables
    
    
    @Override
    public void componentOpened() {
        try {
            // TODO add custom code on component opening
            webpage.setPage("https://www.cs.utexas.edu/~scottm/cs307/codingSamples.htm");
        } catch (IOException ex) {
            Exceptions.printStackTrace(ex);
        }
        
    }

    @Override
    public void componentClosed() {
        // TODO add custom code on component closing
    }

    void writeProperties(java.util.Properties p) {
        // better to version settings since initial version as advocated at
        // http://wiki.apidesign.org/wiki/PropertyFiles
        p.setProperty("version", "1.0");
        // TODO store your settings
    }

    void readProperties(java.util.Properties p) {
        String version = p.getProperty("version");
        // TODO read your settings according to their version
    }
}
